<?php
   $options  = array("ac" => "Acre",
                     "al" => "Alagoas",
                     "ap" => "Amapá",
                     "am" => "Amazonas",
                     "ba" => "Bahia",
                     "ce" => "Ceará",
                     "df" => "Distrito Federal",
                     "pr" => "Paraná",
                     "es" => "Espírito Santo",
                     "go" => "Goiás",
                     "ma" => "Maranhão",
                     "mt" => "Mato Grosso",
                     "ms" => "Mato Grosso do Sul",
                     "sc" => "Santa Catarina",
                     "mg" => "Minas Gerais",
                     "pb" => "Paraíba",
                     "pe" => "Pernanbumco",
                     "pi" => "Piauí",
                     "rn" => "Rio Grande do Norte",
                     "ro" => "Rondônia",
                     "rr" => "Roraima",
                     "se" => "Sergipe",
                     "rs" => "Rio Grande do Norte",
                     "to" => "Tocantins",
                     "sp" => "São Paulo",
                     "rj" => "Rio de Janeiro",
                     "pa" => "Pará",
                    );
?>
